### ISSUE TITLE
`special://` path url not recognized

### ISSUE THREAD

**Issue by roblav96** [patrick-klein/repository.librarytools#1]
@patrick-klein

I'd like to set my managed folder path to:
```
special://userdata/addon_data/script.library.integration.tool/
```
but when I try and run the add-on for the first time it says in a notification:
```
Choose managed folder in settings!
```

The `tail -F kodi.log` spits out:
```
ERROR: Library Integration Tool v0.3.2 --> No managed folder!
```
when I try and run the add-on.

I have a unique backup/restore method I'd like to use but it requires the use of a `special://` path url. Any ideas? Great work and thanks mate! =]

**Comment by patrick-klein** [comment]
I just made `special://userdata/addon_data/script.library.integration.tool/` the default path for the managed folder which should solve your issue.  

Also FYI, this Github repo is for the LibraryTools repository. Issues for the addon should be reported in the [script.library.integration.tool](https://github.com/patrick-klein/script.library.integration.tool) repo.

Thanks for the feedback!  Let me know if there are any other issues / feature requests in the forum or in the addon repo
